### ISSUE TITLE
Trying to adjust for 5120x1440 resolution

### ISSUE THREAD

**Issue by nem8** [josdemmers/NewWorldCompanion#18]
Im trying to adjust for 5120x1440 resolution, but im not clear on how it works..

I run my game in fullscreen, and i selected the 2560x1440 resolution template in the application. 
It seems to work rather well, but it is struggling with some items, i can see the overlay popping up then dissapearing again. On other items it will flicker on and off but if i move my mouse a few pixels it might steady.. 

I also notice that it tends to catch the next item over:
![image](https://user-images.githubusercontent.com/495296/212668357-70ee9af4-7a99-46a3-8cc8-5d434a0c8e89.png)

You say to set the min and max sliders to their extreme low and extreme high, and adjust one step at a time.
Do i need to adjust the sliders, then alt tab to game and hover over an item to let it read, then alt tab out to the application to see the result?

When i tried adjusting it this way, i didnt seem to be able to ever reach a point where it was able to detect anything. I can see what is under my mouse pointer in the small image to the right, but in the larger image (where it will show text detected) it just shows my characters stats (dex, str etc).

I guess im not clear on what "Border" and "Area" thresholds are, is one of these for adjusting which area of the screen in captured? What about the other?

Anything i can do to explain this better? :)

**Comment by josdemmers** [comment]
Looks like you are doing everything correctly.
The 2560x1440 preset should work for 5120x1440 as well. It's the 1440 part that matters.

Regarding the flickering could you check the following:
- First the New World setting, deactivate the "Cap FPS in Background" in New World settings. But as you are playing in fullscreen mode this probably wont have any effect.

- Secondly the flickering could also occur when you have multiple instances of NewWorldCompanion active. Check the Task Manager to make sure there is only one. Thanks for the reminder, I was planning to fix that so that you can run it only once. 

Not sure what you meant by `I also notice that it tends to catch the next item over:`? It can only read the item name where you hover your mouse over.

![image](https://user-images.githubusercontent.com/8627157/212763688-30cb9ead-431d-4461-8c87-6149e036a4e2.png)

I don't think you need to adjust the "Border" and "Area" because the 2560x1440 preset is correct for you. Also it is difficult to adjust on a single monitor, fullscreen setup. Not sure if it's even possible to configure it like that because you can't configure it the moment you alt-tab.
Normally you would use it on a second monitor so you can see what happens in real-time.

Regarding the "Border" and "Area" thresholds. If you look at the screenshot above. The "Border" is border around the items icon. The "Area" is the total area of the icon.

Border:
![image](https://user-images.githubusercontent.com/8627157/212766943-3ddc4706-7107-4786-b34c-b252faf55445.png)

Area:
![image](https://user-images.githubusercontent.com/8627157/212766994-f61f4511-3c76-4738-a1c8-9575b7f6c5b9.png)

Let me know when one of the above suggestions fixes your issue.
