### ISSUE TITLE
Server list

### ISSUE THREAD

**Issue by anndrox** [josdemmers/NewWorldCompanion#25]
Hello!

Will the server list be updated?

**Comment by josdemmers** [comment]
Hi, good to see there is interest in the price overlay.

Price data and servers are not yet using https://nwmp.gaming.tools/ but the previous https://nwmarketprices.com/.
I have already fixed the server list but haven't released it yet because the price data is not working at the moment.

Need to discuss this with the developer of https://nwmp.gaming.tools first.

![image](https://github.com/user-attachments/assets/38d8df4e-4cc2-41c1-aa02-d02b7e33baf1)

**Comment by anndrox** [comment]
Thank you for your prompt reply! Thank you!

**Comment by josdemmers** [comment]
Release v1.13.0.0 is now ready. Server list and price data is working again.
![image](https://github.com/user-attachments/assets/53d57674-0a14-45a2-867a-1aace2949ec5)
