### ISSUE TITLE
TP pricing not lining up

### ISSUE THREAD

**Issue by Marthisdil** [josdemmers/NewWorldCompanion#3]
Version 1.0.4.2

2560x1440 - windows screen res, game full screen res, 2560x1440 setting in config.

![image](https://user-images.githubusercontent.com/98221/165397849-f071c693-ca23-4010-a5a8-796ce3fba40d.png)

![image](https://user-images.githubusercontent.com/98221/165398085-c4e28077-5fc3-4de9-9c5e-069c1996b323.png)

Also, the font size on the pricing info is VERY small (compared to 1.0.4.1)

**Comment by josdemmers** [comment]
Latest update for the pricing overlay was in Release v1.0.3.2.
And font size hasn't been changed since Release v1.0.1.0.

It looks like an issue with your resolution.
Sometimes New World likes to reset your resolution settings in the following cases:
- Cleared steam data and/or game data
- Verify integrity of game files
- Installing updates New World

The only way I was able to reproduce your issue was when my monitor and ingame resolution did not match.

I would recommend to try the following
- Check your monitor resolution, if you have multiple monitors make sure the correct one is set.
- Check ingame resolution to make sure New World did not reset your settings.
  - Restart New world after changing the ingame resolution.

**Comment by Marthisdil** [comment]
It's not game or windows resolution.  As mentioned, wasn't happening in 1.0.4.1.  Updated to 1.0.4.4 just now:

Game resolution:

![image](https://user-images.githubusercontent.com/98221/165556018-8e9a1355-0bd5-4097-9243-45a6c2be2fd7.png)

Windows Resolution:

![image](https://user-images.githubusercontent.com/98221/165556141-7cfd494b-69ff-4b68-8995-960f8ee71c33.png)

Setting in Config section:

![image](https://user-images.githubusercontent.com/98221/165556450-a94beca1-61f7-4573-80e7-4f6af92f3f2c.png)

Result from in-game:

![image](https://user-images.githubusercontent.com/98221/165555869-714902ac-03ab-4de5-b00a-75d27d78f72f.png)

The NW Market Prices scanner is able to scan at 1440 without issue (and it would certainly have issues if it were a game or windows resolution issue).

**Comment by josdemmers** [comment]
There are many different implementations to handle window coordinates. Also both tools are written in a different language. It's too early to exclude anything that could cause this issue.

Would be great if you could share more info about your pc.
- Single or multi monitor setup?
  - What are the resolutions for those monitors.
  - What are the scaling settings for those monitors.
- Do you use any app for downscaling/upscaling your resolution.

Also could you check the following.
Open the Settings.json file in the config folder and set the following setting to true:
```DebugModeActive": true```
While ingame move your mouse to the top left of your game screen. Take a screenshot of the coordinates.
While ingame move your mouse to the bottom right of your game screen. Take a screenshot of the coordinates.
![image](https://user-images.githubusercontent.com/8627157/165571586-d40a4b17-f5ef-45d1-8768-38df18f382e4.png)

**Comment by Marthisdil** [comment]
Happy to share more info!

Multi-monitor setup (primary is a 4k monitor, but I bring the res down to 2560x1440 and have the game at that as I use the NW Marker Prices scanner as well).  Secondary is a 1920x1080 monitor.  Game (as you can see above) is on MOnitor 1 (which is the 1440 res screen)

Scaling, as you see from my windows resolution above is at 100% in windows.

I do not use any app for up/downscaling.

debug enabled
top left:

![image](https://user-images.githubusercontent.com/98221/165583666-2fe13fac-9c45-439e-a48e-265553826ee4.png)

bottom right:

![image](https://user-images.githubusercontent.com/98221/165583818-165a88a9-ae39-472d-a47f-1360aae53a4d.png)

**Comment by Marthisdil** [comment]
Heres something interesting.  After taking the caps above with debug mode...made sure all of the debug config screens showed 2560x1440 res and clicked the load config button.

Went back into the game, and the pricing box is showing in the correct spot (and size), now:

![image](https://user-images.githubusercontent.com/98221/165584182-ad955c23-3c6b-4cf5-9cec-c10c3cd0ca3d.png)

ScreenProcess (under debug)
![image](https://user-images.githubusercontent.com/98221/165584307-c8a0d5f2-f6f8-4443-bb7d-ee85dea8665d.png)

**Comment by josdemmers** [comment]
Great that you have it working again!
I tested both the Config and Debug tabs and looks like the settings are saved fine for both.
Let me know if it happens again then I'll do some extra debugging.

Testing your setup exactly will be difficult because I don't have a 4k monitor. But will see how to handle that if it ever happens again.

**Comment by Marthisdil** [comment]
Understood.  Exiting the app, editing the config and changing the debug to false, going back in the app seems to have kept things displaying properly now too.

will advise if it breaks again!

**Comment by Marthisdil** [comment]
@josdemmers issue is back.  Same as above images, not in debug mode, same resolution/settings.  prices showing off and to the left (like above) and small text,

enabling debug mode and going back in to the app, then debug > screenprocess, setting to 2560x1440 > load config, doing the same for config > screen process and the pricing info shows correctly.

seems like something weird witth the screenprocess setting somehow that only in debug mode and setting on the debug setting fixes it.

**Comment by josdemmers** [comment]
Closed #4 and reopened this one. Easier to have everything in one place.

**Comment by josdemmers** [comment]
Where you able to find out when it comes back?
- Each time you restart the Companion app?
- Each time you restart New World?
- After you restart your pc?
- After you have switched between 4K en 1440p?
- After changing the config in the Companion app?

**Comment by Marthisdil** [comment]
Test process just now:
- rebooted computer
- set windows resolution to 2560x1440, made sure scaling was 100%
- opened Steam
- launched New World
- at login, checked New World resolution was set to 2560x1440, full screen, monitor 1
- launched NW companion, moved screen to monitor 2
- NWC config > screenprocess - changed dropdown to 2560x1440, clicked load config.
- logged into NW

1) moused over something in inventory, pricing data showed off (as above images) to the top left and small text.
2) exited new world, leaving NWC running, relaunched NW, logged in, checked inventory, same issue
3) stayed logged in, exited NWC.  relaunched NWC, config > screenprocess, selected 2560x1440 and clicked load config.  checked inventory same issue
4) exited NWC.  Set debug to true.  relaunced nwc. config > screenprocess, selected 2560x1440, load config.  still had same issue
5) debug > screenprocess, selected 2560x1440, load config.  verified config > screenprocess was still 2560x1440.  moused over inventory item, pricing box showed above item popup with text sized appropriately - works.
6) exited NWC.  exited NW. changed debug to false. relaunched nw. relaunched nwc. logged into game. config > screenprocess, selected 2560x1440, clicked load config. moused over inventory item again pricing showed properly. repeated 2 more times - 2nd and 3rd time, pricing data was off, up to the left and small again.
7) exited nw, exited nwc, rebooted computer, logged back in to everything (confirming windows resolution/scaling). launched nw. launched nwc. config > screenprocess, selected 2560x1440, load config. checked inventory, pricing was still off.

if i turn on debug and do what I did in #5, it seems to fix the issue (debug > screenprocess selection perhaps)?  No explanation why it would continue to work as expected the next time with debug off, but then repeated attempts after, the pricing data would show incorrectly again.

hope the above helps in some way!

**Comment by josdemmers** [comment]
Thank you for the thorough testing!
But I just can't seem to break it :/
I also tried to simulate your 4k > 1440p downscaling by setting mine from 1440p > 1080p.

Your #6 is indeed very strange. You can reproduce it so easily but it just wont happen for me.

The position of the tooltip is influenced by the following.
- Mouse position
- Region of interest (Area around items icon)

Assuming that something goes wrong there the following could help.

1. When it stops working. Can you check the mouse coordinates again for the top left and bottom right positions using "Debug/ScreenCapture"? Do this before pressing the load config button. Not sure if your previous screenshots with those coordinates were before or after you used load config. Otherwise feel free to ignore this.
2. Region of interest depends on your active processes. Could you go to Task Manager -> Details, sort all processes by name and check if there is only one NewWorld.exe

Another possibility is to get it working for the 4K resolution. I would need to increase the area thresholds first in the config tab because the max value is probably too small. Let me know if you are interested and I can create test version for you.

// Edit

One more thing to test. When the tooltip stops working can you go to the Debug/ScreenCountOCR tab?
When you move your mouse to the center of an icon in New World does it show the correct item on that tab? Or is it something completely different?
![image](https://user-images.githubusercontent.com/8627157/166102928-6c39df7e-1356-47d9-940d-761fd2978937.png)

And one final question regarding your #6. Are you also able to reproduce it by only restarting NWC a couple of times. Or does it only occur when you restart both NWC and NW?

**Comment by josdemmers** [comment]
Improvement made for 4k screens in release v1.0.6.0.
No further updates planned.
